object frUpdate: TfrUpdate
  Left = 0
  Top = 0
  Width = 268
  Height = 442
  AutoScroll = False
  TabOrder = 0
  object imLogo: TspPngImageView
    Left = 0
    Top = 0
    Width = 268
    Height = 90
    DoubleBuffered = False
    ReflectionEffect = False
    PngImageList = ComponentModuleWindow.ilLoginLogo
    ImageIndex = 0
    Align = alTop
    Center = True
    FlagIndex = 0
    DrawFlag = False
  end
  object lbStatus: TspSkinShadowLabel
    Left = 24
    Top = 220
    Width = 217
    Height = 25
    HintImageIndex = 0
    DrawDefault = True
    AlphaBlend = False
    AlphaBlendValue = 200
    UseSkinCursor = False
    AutoSize = False
    Alignment = taCenter
    DoubleBuffered = True
    ShadowSize = 2
    ShadowOffset = 1
    ShadowColor = clBlack
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
  end
  object gaugeUpdateProgress: TspSkinGauge
    Left = 24
    Top = 244
    Width = 217
    Height = 20
    HintImageIndex = 0
    TabOrder = 0
    Visible = False
    DrawDefault = True
    SkinData = ComponentModuleWindow.sppLogin
    SkinDataName = 'gauge'
    AlphaBlend = False
    AlphaBlendValue = 200
    UseSkinCursor = False
    DefaultFont.Charset = DEFAULT_CHARSET
    DefaultFont.Color = clWindowText
    DefaultFont.Height = 14
    DefaultFont.Name = 'Arial'
    DefaultFont.Style = []
    UseSkinFont = True
    DefaultWidth = 0
    DefaultHeight = 0
    ProgressAnimationPause = 1000
    UseSkinSize = True
    TextAlphaBlend = False
    TextAlphaBlendValue = 200
    ShowProgressText = False
    ShowPercent = False
    MinValue = 0
    MaxValue = 100
    Value = 50
    Vertical = False
  end
  object SkinFrame: TspSkinFrame
    SkinData = ComponentModuleWindow.sppLogin
    DrawBackground = True
    CtrlsSkinData = ComponentModuleWindow.sppLogin
    Left = 8
    Top = 8
  end
  object ZipForge: TZipForge
    ExtractCorruptedFiles = False
    CompressionLevel = clMax
    CompressionMode = 9
    CurrentVersion = '5.06 '
    SpanningMode = smNone
    SpanningOptions.AdvancedNaming = False
    SpanningOptions.VolumeSize = vsAutoDetect
    Options.FlushBuffers = True
    Options.OEMFileNames = True
    InMemory = False
    OnOverallProgress = ZipForgeOverallProgress
    OnProcessFileFailure = ZipForgeProcessFileFailure
    OnDiskFull = ZipForgeDiskFull
    Zip64Mode = zmDisabled
    UnicodeFilenames = False
    EncryptionMethod = caPkzipClassic
    Left = 40
    Top = 8
  end
  object httpUpdate: THttpCli
    LocalAddr = '0.0.0.0'
    ProxyPort = '80'
    Agent = 'Mozilla/4.0 (compatible; ICS)'
    Accept = 'image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, */*'
    NoCache = False
    ContentTypePost = 'application/x-www-form-urlencoded'
    MultiThreaded = False
    RequestVer = '1.0'
    FollowRelocation = True
    LocationChangeMaxCount = 5
    ServerAuth = httpAuthNone
    ProxyAuth = httpAuthNone
    BandwidthLimit = 10000
    BandwidthSampling = 1000
    Options = []
    Timeout = 10
    OnDocBegin = httpUpdateDocBegin
    OnDocData = httpUpdateDocData
    SocksAuthentication = socksNoAuthentication
    Left = 72
    Top = 8
  end
  object tiHideUpdateFrame: TTimer
    Enabled = False
    Interval = 3000
    OnTimer = tiHideUpdateFrameTimer
    Left = 104
    Top = 8
  end
end
