unit SharedVars;

interface

type
  TCountry = record
               Code, Name : String;
             end;

  TFileHash = record
                Filename : String;
                Hash     : String[32];
              end;

  TWarcraftHashes = Array[0..4] of TFileHash;
  TWarcraftHashVersion = record
                           Version : String;
                           Hashes  : TWarcraftHashes;
                         end;

  TVKey = record
            KeyCode : Word;
            KeyName : String;
          end;

const
  CLIENT_VERSION       = 'v2.11b';

  CLIENT_INSTANCEMUTEX = 'DarerClientInstanceMutex';
  CRYPT_PASS           = 'kw!@3sdk@5sdfln41$82384hsa,32ja123,2567@(&^2134mn @7675';
  URL_API              = 'http://www.darer.com/apiv2/';
  URL_VERSION          = 'http://update.darer.com/updates/currentversion';
  URL_USER_AVATAR_145  = 'http://www.darer.com/uploads/avatar/155x155/default/';
  URL_USER_AVATAR_35   = 'http://www.darer.com/uploads/avatar/35x35/';
  URL_CAPTCHA          = 'http://www.darer.com/captcha/default';
  SOUND_DIR            = 'sounds\';
  PATCH_DIR            = '%appdata%\Darer\patches\';
  CACHE_DIR            = '%appdata%\Darer\cache\';
  GPROXY_CFG           = '%appdata%\Darer\GProxy\';
  GPROXY_EXE           = 'GProxy\gproxy.exe';

  VAR_LEVEL_BASE  = 10;
  VAR_LEVEL_POWER = 2.2;

  ROOM_COUNT = 3;
  ROOMS : Array[0..ROOM_COUNT - 1] of String = ('Beginners', 'Advanced', 'Experts');

  LATEST_WC3_VERSION   = '1.26a';

  BOTS_COUNT = 3;
  BOTS_NAMES : Array[0..BOTS_COUNT - 1] of String = ('psi', 'bot??', 'System');

  DOWNLOAD_MAPS_LINK   = 'http://update.darer.com/maps/download/';
  DOWNLOAD_MAPS_COUNT  = 59;
  DOWNLOAD_MAPS        : Array[0..DOWNLOAD_MAPS_COUNT - 1] of String = (
                                                                        'DotA Allstars v6.48.w3x',
                                                                        'DotA Allstars v6.48b.w3x',
                                                                        'DotA Allstars v6.49.w3x',
                                                                        'DotA Allstars v6.49b.w3x',
                                                                        'DotA Allstars v6.49c.w3x',
                                                                        'DotA Allstars v6.50.w3x',
                                                                        'DotA Allstars v6.50b.w3x',
                                                                        'DotA Allstars v6.51.w3x',
                                                                        'DotA Allstars v6.52.w3x',
                                                                        'DotA Allstars v6.52b.w3x',
                                                                        'DotA Allstars v6.52c.w3x',
                                                                        'DotA Allstars v6.52d.w3x',
                                                                        'DotA Allstars v6.52e.w3x',
                                                                        'DotA Allstars v6.53.w3x',
                                                                        'DotA Allstars v6.54.w3x',
                                                                        'DotA Allstars v6.54b.w3x',
                                                                        'DotA Allstars v6.55.w3x',
                                                                        'DotA Allstars v6.55b.w3x',
                                                                        'DotA Allstars v6.56.w3x',
                                                                        'DotA Allstars v6.57.w3x',
                                                                        'DotA Allstars v6.57b.w3x',
                                                                        'DotA Allstars v6.58.w3x',
                                                                        'DotA Allstars v6.58b.w3x',
                                                                        'DotA Allstars v6.59.w3x',
                                                                        'DotA Allstars v6.59b.w3x',
                                                                        'DotA Allstars v6.59c.w3x',
                                                                        'DotA Allstars v6.59d.w3x',
                                                                        'DotA Allstars v6.60.w3x',
                                                                        'DotA Allstars v6.60b.w3x',
                                                                        'DotA Allstars v6.61.w3x',
                                                                        'DotA Allstars v6.61b.w3x',
                                                                        'DotA Allstars v6.61c.w3x',
                                                                        'DotA Allstars v6.62.w3x',
                                                                        'DotA Allstars v6.62b.w3x',
                                                                        'DotA Allstars v6.63.w3x',
                                                                        'DotA Allstars v6.63b.w3x',
                                                                        'DotA Allstars v6.64.w3x',
                                                                        'DotA Allstars v6.65.w3x',
                                                                        'DotA Allstars v6.66.w3x',
                                                                        'DotA Allstars v6.66b.w3x',
                                                                        'DotA Allstars v6.67.w3x',
                                                                        'DotA Allstars v6.67b.w3x',
                                                                        'DotA Allstars v6.67c.w3x',
                                                                        'DotA v6.68.w3x',
                                                                        'DotA v6.68c.w3x',
                                                                        'DotA v6.69.w3x',
                                                                        'DotA v6.69b.w3x',
                                                                        'DotA v6.69c.w3x',
                                                                        'DotA v6.70.w3x',
                                                                        'DotA v6.70b.w3x',
                                                                        'DotA v6.70c.w3x',
                                                                        'DotA v6.71.w3x',
                                                                        'DotA v6.71b.w3x',
                                                                        'DotA v6.72.w3x',
                                                                        'DotA v6.72b.w3x',
                                                                        'DotA v6.72c.w3x',
                                                                        'DotA v6.72d.w3x',
                                                                        'DotA v6.72e.w3x',
                                                                        'DotA v6.72f.w3x'
                                                                       );

  HASHES_FILE_WAR3      = 'war3.exe';
  HASHES_FILE_GAME      = 'game.dll';
  HASHES_FILE_STORM     = 'Storm.dll';
  HASHES_FILE_WAR3PATCH = 'War3Patch.mpq';
  HASHES_FILE_WAR3LOCAL = 'War3xlocal.mpq';
  WARHASHES_COUNT = 3;

type
  TWarhashes = Array[0..WARHASHES_COUNT - 1] of TWarcraftHashVersion;

const
  WARHASHES_EN : TWarhashes = ( // english
                                (Version: '1.26a';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'D0FCFE5155E2C8AB858C128147F916FB'),
                                          (Filename: HASHES_FILE_GAME;      Hash: 'BA5A2FE39F08A8272DDB1A45DFB62569'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '9A2B885CABCADF8C9BDBA934F88A818F'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '6CA1234E93FAE86BB5100A4F32C515E0'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '52A151CC996DB3913836931E61175197'))),
                                (Version: '1.25b';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'BC7FEA535504B917A0E5EBA268F15AAF'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '6FD64C5D05FC3E598B1AE31D5878BC87'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '93E675E5EE87C8FBD0D23074C824DF56'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '0E0969A6FE7A048BD1D03E4CE2D832DA'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '52A151CC996DB3913836931E61175197'))),
                                (Version: '1.24e';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: '54A8EEBD28B7EA4482F54B6A162867ED'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '047344F31D198BDD42DD2D37279CA9CB'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '7F6E6C2403FFB6B705203920B3FC76A4'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '64589CDDBAE67411A3A5FA640DBE62F5'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '52A151CC996DB3913836931E61175197')))
                               );
  WARHASHES_RU : TWarhashes = ( // russian
                                (Version: '1.26a';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'D0FCFE5155E2C8AB858C128147F916FB'),
                                          (Filename: HASHES_FILE_GAME;      Hash: 'BA5A2FE39F08A8272DDB1A45DFB62569'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '9A2B885CABCADF8C9BDBA934F88A818F'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '375FE551B1B6CE168995E5C62C1509C8'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '3DCCD768062AC0248BDFECB17BEE7461'))),
                                (Version: '1.25b';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'BC7FEA535504B917A0E5EBA268F15AAF'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '6FD64C5D05FC3E598B1AE31D5878BC87'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '93E675E5EE87C8FBD0D23074C824DF56'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '6A2F8A7DD64E29F0AE023495F94B4411'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '3DCCD768062AC0248BDFECB17BEE7461'))),
                                (Version: '1.24e';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: '54A8EEBD28B7EA4482F54B6A162867ED'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '047344F31D198BDD42DD2D37279CA9CB'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '7F6E6C2403FFB6B705203920B3FC76A4'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: 'AAC2FEE2514B9769628AA755DD5B2085'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '3DCCD768062AC0248BDFECB17BEE7461')))
                               );
  WARHASHES_TW : TWarhashes = ( // chinese traditional
                                (Version: '1.26a';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'D0FCFE5155E2C8AB858C128147F916FB'),
                                          (Filename: HASHES_FILE_GAME;      Hash: 'BA5A2FE39F08A8272DDB1A45DFB62569'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '9A2B885CABCADF8C9BDBA934F88A818F'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '88E8920218B1DBE36216935BAFB0B6A1'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '9E477EE5D2E29B1BED66846F46A7872D'))),
                                (Version: '1.25b';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: 'BC7FEA535504B917A0E5EBA268F15AAF'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '6FD64C5D05FC3E598B1AE31D5878BC87'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '93E675E5EE87C8FBD0D23074C824DF56'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: '82E52B75F059359ED561C7003A11E654'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '9E477EE5D2E29B1BED66846F46A7872D'))),
                                (Version: '1.24e';
                                 Hashes: ((Filename: HASHES_FILE_WAR3;      Hash: '54A8EEBD28B7EA4482F54B6A162867ED'),
                                          (Filename: HASHES_FILE_GAME;      Hash: '047344F31D198BDD42DD2D37279CA9CB'),
                                          (Filename: HASHES_FILE_STORM;     Hash: '7F6E6C2403FFB6B705203920B3FC76A4'),
                                          (Filename: HASHES_FILE_WAR3PATCH; Hash: 'A8A4D6C2C7FDD457CDB42A13C482159A'),
                                          (Filename: HASHES_FILE_WAR3LOCAL; Hash: '9E477EE5D2E29B1BED66846F46A7872D')))
                               );

  VKEYS_COUNT = 106;
  VKEYS : Array[0..VKEYS_COUNT - 1] of TVKey = (
                                                (KeyCode: $08; KeyName: 'Bckspc'),
                                                (KeyCode: $09; KeyName: 'Tab'),
                                                (KeyCode: $0C; KeyName: 'Clear'),
                                                (KeyCode: $0D; KeyName: 'Enter'),
                                                (KeyCode: $10; KeyName: 'Shift'),
                                                (KeyCode: $11; KeyName: 'Ctrl'),
                                                (KeyCode: $12; KeyName: 'Alt'),
                                                (KeyCode: $13; KeyName: 'Pause'),
                                                (KeyCode: $14; KeyName: 'Caps'),
                                                (KeyCode: $1B; KeyName: 'Escape'),
                                                (KeyCode: $20; KeyName: 'Space'),
                                                (KeyCode: $21; KeyName: 'PgUp'),
                                                (KeyCode: $22; KeyName: 'PgDn'),
                                                (KeyCode: $23; KeyName: 'End'),
                                                (KeyCode: $24; KeyName: 'Home'),
                                                (KeyCode: $25; KeyName: 'LArrow'),
                                                (KeyCode: $26; KeyName: 'UArrow'),
                                                (KeyCode: $27; KeyName: 'RArrow'),
                                                (KeyCode: $28; KeyName: 'DArrow'),
                                                (KeyCode: $29; KeyName: 'Select'),
                                                (KeyCode: $2B; KeyName: 'Exec'),
                                                (KeyCode: $2C; KeyName: 'PrScr'),
                                                (KeyCode: $2D; KeyName: 'Ins'),
                                                (KeyCode: $2E; KeyName: 'Del'),
                                                (KeyCode: $2F; KeyName: 'Help'),
                                                (KeyCode: $30; KeyName: '0'),
                                                (KeyCode: $31; KeyName: '1'),
                                                (KeyCode: $32; KeyName: '2'),
                                                (KeyCode: $33; KeyName: '3'),
                                                (KeyCode: $34; KeyName: '4'),
                                                (KeyCode: $35; KeyName: '5'),
                                                (KeyCode: $36; KeyName: '6'),
                                                (KeyCode: $37; KeyName: '7'),
                                                (KeyCode: $38; KeyName: '8'),
                                                (KeyCode: $39; KeyName: '9'),
                                                (KeyCode: $41; KeyName: 'A'),
                                                (KeyCode: $42; KeyName: 'B'),
                                                (KeyCode: $43; KeyName: 'C'),
                                                (KeyCode: $44; KeyName: 'D'),
                                                (KeyCode: $45; KeyName: 'E'),
                                                (KeyCode: $46; KeyName: 'F'),
                                                (KeyCode: $47; KeyName: 'G'),
                                                (KeyCode: $48; KeyName: 'H'),
                                                (KeyCode: $49; KeyName: 'I'),
                                                (KeyCode: $4A; KeyName: 'J'),
                                                (KeyCode: $4B; KeyName: 'K'),
                                                (KeyCode: $4C; KeyName: 'L'),
                                                (KeyCode: $4D; KeyName: 'M'),
                                                (KeyCode: $4E; KeyName: 'N'),
                                                (KeyCode: $4F; KeyName: 'O'),
                                                (KeyCode: $50; KeyName: 'P'),
                                                (KeyCode: $51; KeyName: 'Q'),
                                                (KeyCode: $52; KeyName: 'R'),
                                                (KeyCode: $53; KeyName: 'S'),
                                                (KeyCode: $54; KeyName: 'T'),
                                                (KeyCode: $55; KeyName: 'U'),
                                                (KeyCode: $56; KeyName: 'V'),
                                                (KeyCode: $57; KeyName: 'W'),
                                                (KeyCode: $58; KeyName: 'X'),
                                                (KeyCode: $59; KeyName: 'Y'),
                                                (KeyCode: $5A; KeyName: 'Z'),
                                                (KeyCode: $5B; KeyName: 'LWin'),
                                                (KeyCode: $5C; KeyName: 'RWin'),
                                                (KeyCode: $5D; KeyName: 'AppKey'),
                                                (KeyCode: $60; KeyName: 'Num0'),
                                                (KeyCode: $61; KeyName: 'Num1'),
                                                (KeyCode: $62; KeyName: 'Num2'),
                                                (KeyCode: $63; KeyName: 'Num3'),
                                                (KeyCode: $64; KeyName: 'Num4'),
                                                (KeyCode: $65; KeyName: 'Num5'),
                                                (KeyCode: $66; KeyName: 'Num6'),
                                                (KeyCode: $67; KeyName: 'Num7'),
                                                (KeyCode: $68; KeyName: 'Num8'),
                                                (KeyCode: $69; KeyName: 'Num9'),
                                                (KeyCode: $6A; KeyName: '*'),
                                                (KeyCode: $6B; KeyName: '+'),
                                                (KeyCode: $6C; KeyName: ','),
                                                (KeyCode: $6D; KeyName: '-'),
                                                (KeyCode: $6E; KeyName: '.'),
                                                (KeyCode: $6F; KeyName: '/'),
                                                (KeyCode: $70; KeyName: 'F1'),
                                                (KeyCode: $71; KeyName: 'F2'),
                                                (KeyCode: $72; KeyName: 'F3'),
                                                (KeyCode: $73; KeyName: 'F4'),
                                                (KeyCode: $74; KeyName: 'F5'),
                                                (KeyCode: $75; KeyName: 'F6'),
                                                (KeyCode: $76; KeyName: 'F7'),
                                                (KeyCode: $77; KeyName: 'F8'),
                                                (KeyCode: $78; KeyName: 'F9'),
                                                (KeyCode: $79; KeyName: 'F10'),
                                                (KeyCode: $7A; KeyName: 'F11'),
                                                (KeyCode: $7B; KeyName: 'F12'),
                                                (KeyCode: $7C; KeyName: 'F13'),
                                                (KeyCode: $7D; KeyName: 'F14'),
                                                (KeyCode: $7E; KeyName: 'F15'),
                                                (KeyCode: $7F; KeyName: 'F16'),
                                                (KeyCode: $80; KeyName: 'F17'),
                                                (KeyCode: $81; KeyName: 'F18'),
                                                (KeyCode: $82; KeyName: 'F19'),
                                                (KeyCode: $83; KeyName: 'F20'),
                                                (KeyCode: $84; KeyName: 'F21'),
                                                (KeyCode: $85; KeyName: 'F22'),
                                                (KeyCode: $86; KeyName: 'F23'),
                                                (KeyCode: $87; KeyName: 'F24'),
                                                (KeyCode: $90; KeyName: 'NumLck'),
                                                (KeyCode: $91; KeyName: 'ScrollLck'));

  COUNTRY_LIST_COUNT   = 218;
  COUNTRY_LIST         : Array[0..COUNTRY_LIST_COUNT - 1] of TCountry = ((Code: 'World'; Name: 'World'),
                                                                         (Code: 'AF'; Name: 'Afghanistan'),
                                                                         (Code: 'AL'; Name: 'Albania'),
                                                                         (Code: 'DZ'; Name: 'Algeria'),
                                                                         (Code: 'AS'; Name: 'American Samoa'),
                                                                         (Code: 'AD'; Name: 'Andorra'),
                                                                         (Code: 'AO'; Name: 'Angola'),
                                                                         (Code: 'AI'; Name: 'Anguilla'),
                                                                         (Code: 'AQ'; Name: 'Antarctica'),
                                                                         (Code: 'AG'; Name: 'Antigua and Barbuda'),
                                                                         (Code: 'AR'; Name: 'Argentina'),
                                                                         (Code: 'AM'; Name: 'Armenia'),
                                                                         (Code: 'AW'; Name: 'Aruba'),
                                                                         (Code: 'AU'; Name: 'Australia'),
                                                                         (Code: 'AT'; Name: 'Austria'),
                                                                         (Code: 'AZ'; Name: 'Azerbaijan'),
                                                                         (Code: 'BS'; Name: 'Bahamas'),
                                                                         (Code: 'BH'; Name: 'Bahrain'),
                                                                         (Code: 'BD'; Name: 'Bangladesh'),
                                                                         (Code: 'BB'; Name: 'Barbados'),
                                                                         (Code: 'BY'; Name: 'Belarus'),
                                                                         (Code: 'BE'; Name: 'Belgium'),
                                                                         (Code: 'BZ'; Name: 'Belize'),
                                                                         (Code: 'BJ'; Name: 'Benin'),
                                                                         (Code: 'BM'; Name: 'Bermuda'),
                                                                         (Code: 'BT'; Name: 'Bhutan'),
                                                                         (Code: 'BO'; Name: 'Bolivia'),
                                                                         (Code: 'BA'; Name: 'Bosnia and Herzegovina'),
                                                                         (Code: 'BW'; Name: 'Botswana'),
                                                                         (Code: 'BR'; Name: 'Brazil'),
                                                                         (Code: 'BN'; Name: 'Brunei'),
                                                                         (Code: 'BG'; Name: 'Bulgaria'),
                                                                         (Code: 'BF'; Name: 'Burkina Faso'),
                                                                         (Code: 'BI'; Name: 'Burundi'),
                                                                         (Code: 'KH'; Name: 'Cambodia'),
                                                                         (Code: 'CM'; Name: 'Cameroon'),
                                                                         (Code: 'CA'; Name: 'Canada'),
                                                                         (Code: 'CV'; Name: 'Cape Verde'),
                                                                         (Code: 'KY'; Name: 'Cayman Islands'),
                                                                         (Code: 'CF'; Name: 'Central African Republic'),
                                                                         (Code: 'TD'; Name: 'Chad'),
                                                                         (Code: 'CL'; Name: 'Chile'),
                                                                         (Code: 'CN'; Name: 'China'),
                                                                         (Code: 'CO'; Name: 'Colombia'),
                                                                         (Code: 'KM'; Name: 'Comoros'),
                                                                         (Code: 'CG'; Name: 'Republic of the Congo'),
                                                                         (Code: 'CD'; Name: 'Democratic Republic of the Congo'),
                                                                         (Code: 'CR'; Name: 'Costa Rica'),
                                                                         (Code: 'CI'; Name: 'Cote dIvoire'),
                                                                         (Code: 'HR'; Name: 'Croatia'),
                                                                         (Code: 'CU'; Name: 'Cuba'),
                                                                         (Code: 'CY'; Name: 'Cyprus'),
                                                                         (Code: 'CZ'; Name: 'Czech Republic'),
                                                                         (Code: 'DK'; Name: 'Denmark'),
                                                                         (Code: 'DJ'; Name: 'Djibouti'),
                                                                         (Code: 'DM'; Name: 'Dominica'),
                                                                         (Code: 'DO'; Name: 'Dominican Republic'),
                                                                         (Code: 'EC'; Name: 'Ecuador'),
                                                                         (Code: 'EG'; Name: 'Egypt'),
                                                                         (Code: 'SV'; Name: 'El Salvador'),
                                                                         (Code: 'GQ'; Name: 'Equatorial Guinea'),
                                                                         (Code: 'ER'; Name: 'Eritrea'),
                                                                         (Code: 'EE'; Name: 'Estonia'),
                                                                         (Code: 'ET'; Name: 'Ethiopia'),
                                                                         (Code: 'FK'; Name: 'Falkland Islands'),
                                                                         (Code: 'FO'; Name: 'Faroes'),
                                                                         (Code: 'FJ'; Name: 'Fiji'),
                                                                         (Code: 'FI'; Name: 'Finland'),
                                                                         (Code: 'FR'; Name: 'France'),
                                                                         (Code: 'GA'; Name: 'Gabon'),
                                                                         (Code: 'GM'; Name: 'Gambia'),
                                                                         (Code: 'GE'; Name: 'Georgia'),
                                                                         (Code: 'DE'; Name: 'Germany'),
                                                                         (Code: 'GH'; Name: 'Ghana'),
                                                                         (Code: 'GR'; Name: 'Greece'),
                                                                         (Code: 'GL'; Name: 'Greenland'),
                                                                         (Code: 'GD'; Name: 'Grenada'),
                                                                         (Code: 'GU'; Name: 'Guam'),
                                                                         (Code: 'GT'; Name: 'Guatemala'),
                                                                         (Code: 'GN'; Name: 'Guinea'),
                                                                         (Code: 'GW'; Name: 'Guinea Bissau'),
                                                                         (Code: 'GY'; Name: 'Guyana'),
                                                                         (Code: 'HT'; Name: 'Haiti'),
                                                                         (Code: 'VA'; Name: 'Vatican City'),
                                                                         (Code: 'HN'; Name: 'Honduras'),
                                                                         (Code: 'HK'; Name: 'Hong Kong'),
                                                                         (Code: 'HU'; Name: 'Hungary'),
                                                                         (Code: 'IS'; Name: 'Iceland'),
                                                                         (Code: 'IN'; Name: 'India'),
                                                                         (Code: 'ID'; Name: 'Indonesia'),
                                                                         (Code: 'IR'; Name: 'Iran'),
                                                                         (Code: 'IQ'; Name: 'Iraq'),
                                                                         (Code: 'IE'; Name: 'Ireland'),
                                                                         (Code: 'IL'; Name: 'Israel'),
                                                                         (Code: 'IT'; Name: 'Italy'),
                                                                         (Code: 'JM'; Name: 'Jamaica'),
                                                                         (Code: 'JP'; Name: 'Japan'),
                                                                         (Code: 'JO'; Name: 'Jordan'),
                                                                         (Code: 'KZ'; Name: 'Kazakhstan'),
                                                                         (Code: 'KE'; Name: 'Kenya'),
                                                                         (Code: 'KI'; Name: 'Kiribati'),
                                                                         (Code: 'KP'; Name: 'North Korea'),
                                                                         (Code: 'KR'; Name: 'South Korea'),
                                                                         (Code: 'KW'; Name: 'Kuwait'),
                                                                         (Code: 'KG'; Name: 'Kyrgyzstan'),
                                                                         (Code: 'LA'; Name: 'Laos'),
                                                                         (Code: 'LV'; Name: 'Latvia'),
                                                                         (Code: 'LB'; Name: 'Lebanon'),
                                                                         (Code: 'LS'; Name: 'Lesotho'),
                                                                         (Code: 'LR'; Name: 'Liberia'),
                                                                         (Code: 'LY'; Name: 'Libya'),
                                                                         (Code: 'LI'; Name: 'Liechtenstein'),
                                                                         (Code: 'LT'; Name: 'Lithuania'),
                                                                         (Code: 'LU'; Name: 'Luxembourg'),
                                                                         (Code: 'MK'; Name: 'Macedonia'),
                                                                         (Code: 'MG'; Name: 'Madagascar'),
                                                                         (Code: 'MW'; Name: 'Malawi'),
                                                                         (Code: 'MY'; Name: 'Malaysia'),
                                                                         (Code: 'MV'; Name: 'Maldives'),
                                                                         (Code: 'ML'; Name: 'Mali'),
                                                                         (Code: 'MT'; Name: 'Malta'),
                                                                         (Code: 'MH'; Name: 'Marshall Islands'),
                                                                         (Code: 'MR'; Name: 'Mauritania'),
                                                                         (Code: 'MU'; Name: 'Mauritius'),
                                                                         (Code: 'MX'; Name: 'Mexico'),
                                                                         (Code: 'FM'; Name: 'Micronesia'),
                                                                         (Code: 'MD'; Name: 'Moldova'),
                                                                         (Code: 'MC'; Name: 'Monaco'),
                                                                         (Code: 'MN'; Name: 'Mongolia'),
                                                                         (Code: 'MS'; Name: 'Montserrat'),
                                                                         (Code: 'MA'; Name: 'Morocco'),
                                                                         (Code: 'MZ'; Name: 'Mozambique'),
                                                                         (Code: 'MM'; Name: 'Myanmar'),
                                                                         (Code: 'NA'; Name: 'Namibia'),
                                                                         (Code: 'NR'; Name: 'Nauru'),
                                                                         (Code: 'NP'; Name: 'Nepal'),
                                                                         (Code: 'NL'; Name: 'Netherlands'),
                                                                         (Code: 'AN'; Name: 'Netherlands Antilles'),
                                                                         (Code: 'NZ'; Name: 'New Zealand'),
                                                                         (Code: 'NI'; Name: 'Nicaragua'),
                                                                         (Code: 'NE'; Name: 'Niger'),
                                                                         (Code: 'NG'; Name: 'Nigeria'),
                                                                         (Code: 'NF'; Name: 'Norfolk Island'),
                                                                         (Code: 'MP'; Name: 'Northern Mariana Islands'),
                                                                         (Code: 'NO'; Name: 'Norway'),
                                                                         (Code: 'OM'; Name: 'Oman'),
                                                                         (Code: 'PK'; Name: 'Pakistan'),
                                                                         (Code: 'PW'; Name: 'Palau'),
                                                                         (Code: 'PS'; Name: 'Palestine'),
                                                                         (Code: 'PA'; Name: 'Panama'),
                                                                         (Code: 'PG'; Name: 'Papua New Guinea'),
                                                                         (Code: 'PY'; Name: 'Paraguay'),
                                                                         (Code: 'PE'; Name: 'Peru'),
                                                                         (Code: 'PH'; Name: 'Philippines'),
                                                                         (Code: 'PN'; Name: 'Pitcairn Islands'),
                                                                         (Code: 'PL'; Name: 'Poland'),
                                                                         (Code: 'PT'; Name: 'Portugal'),
                                                                         (Code: 'PR'; Name: 'Puerto Rico'),
                                                                         (Code: 'QA'; Name: 'Qatar'),
                                                                         (Code: 'RO'; Name: 'Romania'),
                                                                         (Code: 'RU'; Name: 'Russian Federation'),
                                                                         (Code: 'RW'; Name: 'Rwanda'),
                                                                         (Code: 'SH'; Name: 'Saint Helena'),
                                                                         (Code: 'KN'; Name: 'Saint Kitts and Nevis'),
                                                                         (Code: 'LC'; Name: 'Saint Lucia'),
                                                                         (Code: 'VC'; Name: 'Saint Vincent and the Grenadines'),
                                                                         (Code: 'WS'; Name: 'Samoa'),
                                                                         (Code: 'SM'; Name: 'San Marino'),
                                                                         (Code: 'ST'; Name: 'Sao Tome and Principe'),
                                                                         (Code: 'SA'; Name: 'Saudi Arabia'),
                                                                         (Code: 'SN'; Name: 'Senegal'),
                                                                         (Code: 'RS'; Name: 'Serbia'),
                                                                         (Code: 'SC'; Name: 'Seychelles'),
                                                                         (Code: 'SL'; Name: 'Sierra Leone'),
                                                                         (Code: 'SG'; Name: 'Singapore'),
                                                                         (Code: 'SK'; Name: 'Slovakia'),
                                                                         (Code: 'SI'; Name: 'Slovenia'),
                                                                         (Code: 'SB'; Name: 'Solomon Islands'),
                                                                         (Code: 'SO'; Name: 'Somalia'),
                                                                         (Code: 'ZA'; Name: 'South Africa'),
                                                                         (Code: 'GS'; Name: 'South Georgia and the South Sandwich Islands'),
                                                                         (Code: 'ES'; Name: 'Spain'),
                                                                         (Code: 'LK'; Name: 'Sri Lanka'),
                                                                         (Code: 'SD'; Name: 'Sudan'),
                                                                         (Code: 'SR'; Name: 'Suriname'),
                                                                         (Code: 'SZ'; Name: 'Swaziland'),
                                                                         (Code: 'SE'; Name: 'Sweden'),
                                                                         (Code: 'CH'; Name: 'Switzerland'),
                                                                         (Code: 'SY'; Name: 'Syria'),
                                                                         (Code: 'TW'; Name: 'Taiwan'),
                                                                         (Code: 'TJ'; Name: 'Tajikistan'),
                                                                         (Code: 'TZ'; Name: 'Tanzania'),
                                                                         (Code: 'TH'; Name: 'Thailand'),
                                                                         (Code: 'TL'; Name: 'East_Timor'),
                                                                         (Code: 'TG'; Name: 'Togo'),
                                                                         (Code: 'TO'; Name: 'Tonga'),
                                                                         (Code: 'TT'; Name: 'Trinidad and Tobago'),
                                                                         (Code: 'TN'; Name: 'Tunisia'),
                                                                         (Code: 'TR'; Name: 'Turkey'),
                                                                         (Code: 'TM'; Name: 'Turkmenistan'),
                                                                         (Code: 'TC'; Name: 'Turks and Caicos Islands'),
                                                                         (Code: 'TV'; Name: 'Tuvalu'),
                                                                         (Code: 'UG'; Name: 'Uganda'),
                                                                         (Code: 'UA'; Name: 'Ukraine'),
                                                                         (Code: 'AE'; Name: 'United Arab Emirates'),
                                                                         (Code: 'GB'; Name: 'United Kingdom'),
                                                                         (Code: 'US'; Name: 'United States'),
                                                                         (Code: 'UY'; Name: 'Uruguay'),
                                                                         (Code: 'UZ'; Name: 'Uzbekistan'),
                                                                         (Code: 'VU'; Name: 'Vanuatu'),
                                                                         (Code: 'VE'; Name: 'Venezuela'),
                                                                         (Code: 'VN'; Name: 'Vietnam'),
                                                                         (Code: 'VG'; Name: 'British Virgin Islands'),
                                                                         (Code: 'VI'; Name: 'US Virgin Islands'),
                                                                         (Code: 'EH'; Name: 'Western Sahara'),
                                                                         (Code: 'YE'; Name: 'Yemen'),
                                                                         (Code: 'ZM'; Name: 'Zambia'),
                                                                         (Code: 'ZW'; Name: 'Zimbabwe'));


implementation

end.
